apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
spec:
  selector:
    app: ecommerce-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80       # internal cluster port
      targetPort: 80 # container port
      nodePort: 30080 # NodePort as integer
